---
title: "testing examples"
author: "Nicole Carnegie and Stacey Hancock"
date: "December 2, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(catstats)
```

## One proportion bootstrap CI
```{r}
one_proportion_bootstrap_CI(sample_size = 150, number_successes = 98, number_repetitions = 100,
                      confidence_level = 0.99)

```

## One proportion test
```{r}
one_proportion_test(probability_success = 0.5, 
                    sample_size = 150, 
                    number_repetitions = 100,
                    as_extreme_as = 0.65, 
                    direction = "greater", 
                    summary_measure = "proportion",
                    add_normal = TRUE)
```


## One mean bootstrap CI
```{r}
set.seed(117)
x <- rnorm(25)
m <- mean(x)
one_mean_CI(x,
  summary_measure = "mean",
  number_repetitions = 100,
  confidence_level = 0.95)
```

## One mean test
```{r}
set.seed(117)
x <- rnorm(25)
m <- mean(x)
one_mean_test(x,
  summary_measure = "mean",
  shift = -m,
  as_extreme_as = m,
  direction = "two-sided",
  number_repetitions = 100,
  add_normal = FALSE)

```



## Paired bootstrap CI
```{r}
set.seed(117)
x <- rnorm(25)
y <- x + 1 + rnorm(25, 0, .3)
data <- data.frame(x,y)
paired_bootstrap_CI(data, number_repetitions = 100, confidence_level = 0.9, which_first = 1,
                    summary_measure = "median")

```

## Paired observed plot
```{r}
set.seed(117)
x <- rnorm(25)
y <- x + 1 + rnorm(25, 0, .3)
data <- data.frame(x,y)
paired_observed_plot(data)
```

```{r}
# Test with tibble
data <- tibble(data)
paired_observed_plot(data)
```

## Paired test
```{r}
set.seed(117)
x <- rnorm(25)
y <- x + 1 + rnorm(25, 0, .3)
data <- data.frame(x,y)
obs_diff <- mean(x - y)
paired_test(data, shift = -obs_diff, 
            direction = "two-sided",
            as_extreme_as = obs_diff,
            number_repetitions = 100, 
            which_first = 1,
            add_normal = TRUE, summary_measure = "mean")
```

## Regression bootstrap CI
```{r}
data(mtfires)
mtfires$logHect  <- log(mtfires$Hectares)
regression_bootstrap_CI(logHect~Temperature, data = mtfires, summary_measure = "correlation",
             confidence_level = 0.9, number_repetitions = 1000)

```

## Regression test
```{r}
data(mtfires)
mtfires$logHect  <- log(mtfires$Hectares)
regression_test(logHect~Temperature, data = mtfires,
         direction = "greater", summary_measure = "correlation",
         as_extreme_as = 1.388, number_repetitions = 1000)

```

## Two mean bootstrap CI
```{r}
data(pt)
two_mean_bootstrap_CI(responses~brand, data = pt, first_in_subtraction = "B1",
           number_repetitions = 100, confidence_level = 0.98,
           summary_measure = "median")

```

## Two mean test
```{r}
data(pt)
two_mean_test(responses~brand, data = pt, first_in_subtraction = "B1",
          number_repetitions = 100, as_extreme_as = -.4, direction = "two-sided",
          summary_measure = "mean")

```

## Two proportion bootstrap CI
```{r}
data(pt)
pt$twoSeconds <- ifelse(pt$responses >=2, "Yes", "No")
two_proportion_bootstrap_CI(twoSeconds~brand, data = pt, first_in_subtraction = "B1",
      response_value_numerator = "Yes", number_repetitions = 100, confidence_level = 0.95)


```

## Two proportion test
```{r}
data(pt)
pt$twoSeconds <- ifelse(pt$responses >=2, "Yes", "No")
two_proportion_test(twoSeconds~brand, data = pt, 
                    first_in_subtraction = "B1",
                    response_value_numerator = "Yes",
                    number_repetitions = 100, 
                    as_extreme_as = -.4,
                    direction = "two-sided",
                    add_normal = TRUE)
```

